[wip--need modify config script]fix zeromq subscribe proplem
citahub/cita-common pull request #168
Opened 2018-12-14 02:43 UTC by jerry-yu

* fix read env var to avoid conflict
* use lazy static
fmt

2018-12-25 08:31 UTC, u2 requested changes

2018-12-25 08:31 UTC, u2 commented on pubsub_zeromq/src/lib.rs
> +                    .is_ok()
```
publisher.bind().expect("")
```

2018-12-25 08:31 UTC, u2 commented on pubsub_zeromq/src/lib.rs
> +            info!("synchronizer not need publish !");
What's the meaning of this info?

2018-12-25 08:31 UTC, u2 commented on pubsub_zeromq/src/lib.rs
> +    assert!(
Should not use `assert!` here, the same as others.

2018-12-25 08:31 UTC, u2 commented on pubsub_zeromq/src/lib.rs
> +    );
There are so many duplicated codes.

2018-12-26 08:08 UTC, jerry-yu commented on pubsub_zeromq/src/lib.rs
> +                    .is_ok()
add fixed

2019-02-02 01:33 UTC, u2 commented
Close it firstly, reopen it later if we really need it.

2019-02-18 09:35 UTC, kaikai1024 commented
please fix the comment and conflicts. @jerry-yu

2019-02-22 16:36 UTC, kaikai1024 commented
> please fix the comment and conflicts. @jerry-yu

you can reopen it when you have time.

2019-02-22 16:36 UTC, closed without merging