Impl Signature for String
citahub/cita-common pull request #3
Opened 2017-12-29 03:58 UTC by u2

1. Add `impl From<Signature> for String` for sm2
2. Add missing `#[cfg(feature = "zeromq,kafka,rabbitmq")]` to fix unused import.
3. Set default features

2017-12-30 14:18 UTC, zhangsoledad requested changes

2017-12-30 14:18 UTC, zhangsoledad commented on cita-sm2/src/signature.rs
> +        H520::from(s.clone()).hex()
clone is redundant

2017-12-31 02:57 UTC, u2 commented on cita-sm2/src/signature.rs
> +        H520::from(s.clone()).hex()
Done

2018-01-01 11:48 UTC, zhangsoledad approved these changes

2018-01-01 17:00 UTC, merged